spring.application.name=Work360
server.port=8080

# 1. CONFIGURAÇÃO AZURE - Principal

spring.datasource.azure.url=${DB_AZURE_URL}
spring.datasource.azure.username=${DB_AZURE_USER}
spring.datasource.azure.password=${DB_AZURE_PASS}
spring.datasource.azure.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. CONFIGURAÇÃO ORACLE - Secundário (Foco/Relatórios)
spring.datasource.oracle.url=${DB_ORACLE_URL}
spring.datasource.oracle.username=${DB_ORACLE_USER}
spring.datasource.oracle.password=${DB_ORACLE_PASS}
spring.datasource.oracle.driver-class-name=oracle.jdbc.OracleDriver

# 3. CONFIGURAÇÃO GERAL DO SPRING
springdoc.swagger-ui.operations-sorter=alpha

# 5. Spring AI
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.4
spring.ai.openai.chat.options.max-tokens=5000

# 6. SEGURANÇA (JWT)
api.security.token.secret=${API_SECURITY_TOKEN_SECRET}
