spring.application.name=Work360
server.port=8080

# 1. CONFIGURAÇÃO AZURE - Principal
spring.datasource.azure.url=jdbc:sqlserver://work360-sqlsrv.database.windows.net:1433;database=work360_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.azure.username=admnagado@work360-sqlsrv
spring.datasource.azure.password=Dudu2004-
spring.datasource.azure.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. CONFIGURAÇÃO ORACLE - Secundário (Foco/Relatórios)
spring.datasource.oracle.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.oracle.username=rm558158
spring.datasource.oracle.password=030904
spring.datasource.oracle.driver-class-name=oracle.jdbc.OracleDriver

# 3. CONFIGURAÇÃO GERAL DO SPRING
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# 4. SWAGGER / OPENAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

# 5. Spring AI
spring.ai.openai.api-key=${API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.4
spring.ai.openai.chat.options.max-tokens=5000

# 6. SEGURANÇA (JWT)
api.security.token.secret=${JWT_SECRET:my-secret-key}