spring.application.name=Work360
server.port=8080

# 1. CONFIGURAÇÃO AZURE (SQL SERVER) - Principal
spring.datasource.azure.url=jdbc:sqlserver://work360-sqlsrv.database.windows.net:1433;database=work360_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.azure.username=admnagado@work360-sqlsrv
spring.datasource.azure.password=Dudu2004-
spring.datasource.azure.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. CONFIGURAÇÃO ORACLE (FIAP) - Secundário (Foco/Relatórios)
spring.datasource.oracle.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.oracle.username=rm555307
spring.datasource.oracle.password=210905
spring.datasource.oracle.driver-class-name=oracle.jdbc.OracleDriver

# 3. CONFIGURAÇÃO GERAL DO SPRING (Obrigatório para Multi-Datasource)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# 4. SWAGGER / OPENAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

# 5. INTELIGÊNCIA ARTIFICIAL (Spring AI)
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.4
spring.ai.openai.chat.options.max-tokens=5000

# 6. SEGURANÇA (JWT)
api.security.token.secret=wk360_s3cr3t_KEY_8fc912a1d9eb4c2f98b734e0aa1c45fdc7f2d6a57e91a0d8f4dbf13e6b92c8f1